frostyfridays:
  outputs:
    dev:
      account: yt05267.eu-west-2.aws
      database: frosty
      password: 7lOQo0c@H4M%
      role: sysadmin
      schema: challenges
      threads: 1
      type: snowflake
      user: scallybrian
      warehouse: compute_wh
  target: dev
